const mongoose = require('mongoose');

const TimetableSchema = new mongoose.Schema({
  instituteId: { type: mongoose.Schema.Types.ObjectId, ref: 'Institute', required: true },
  generatedAt: { type: Date, default: Date.now },
  semester: String,
  department: String,
  scheduleData: mongoose.Schema.Types.Mixed // Stores the JSON generated by AI
});

module.exports = mongoose.model('Timetable', TimetableSchema);